import os
import time
import logging

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------

DB_HOST = os.getenv("DB_HOST", "postgres")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "eyestream")
DB_USER = os.getenv("DB_USER", "eyestream")
DB_PASSWORD = os.getenv("DB_PASSWORD", "eyestream")


# ---------------------------------------------------------------------
# Connection helpers
# ---------------------------------------------------------------------

def make_conninfo() -> str:
    return (
        f"host={DB_HOST} port={DB_PORT} dbname={DB_NAME} "
        f"user={DB_USER} password={DB_PASSWORD}"
    )


def wait_for_db(max_attempts: int = 30, delay_seconds: int = 2):
    for attempt in range(max_attempts):
        try:
            with psycopg.connect(make_conninfo()):
                return
        except Exception as exc:
            logger.warning("DB not ready (attempt %d/%d): %s", attempt + 1, max_attempts, exc)
            time.sleep(delay_seconds)
    raise RuntimeError("Could not connect to database after %d attempts" % max_attempts)


# ---------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------

def ensure_schema(conn):
    conn.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS categories (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            created_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS videos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            orig_name TEXT,
            stored_name TEXT,
            uploaded_at TIMESTAMPTZ,
            owner_email TEXT,
            status TEXT,
            progress INTEGER DEFAULT 0,
            playlist_url TEXT,
            poster_url TEXT,
            error TEXT,
            started_at TIMESTAMPTZ,
            ffmpeg_pid INTEGER,
            cancel_requested INTEGER DEFAULT 0,
            eta_seconds INTEGER,
            encoded_at TIMESTAMPTZ,
            duration_seconds DOUBLE PRECISION,
            streams_json TEXT,
            queued_at TIMESTAMPTZ,
            note TEXT DEFAULT '',
            category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
            cpu_percent INTEGER,
            disabled INTEGER DEFAULT 0
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS referer_ignore (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pattern TEXT NOT NULL UNIQUE
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS activity_log (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ts TIMESTAMPTZ DEFAULT now(),
            user_email TEXT,
            action TEXT,
            target TEXT,
            detail TEXT
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS worker_heartbeat (
            id INTEGER PRIMARY KEY DEFAULT 1,
            last_seen TIMESTAMPTZ,
            status TEXT,
            cpu_percent INTEGER
        )
        """
    )

    # Seed default ignore patterns
    from helpers import REFERER_IGNORE_SEEDS
    for p in [s.strip() for s in REFERER_IGNORE_SEEDS.split(",") if s.strip()]:
        conn.execute(
            "INSERT INTO referer_ignore (pattern) VALUES (%s) ON CONFLICT DO NOTHING",
            (p,),
        )

    # Indexes
    conn.execute("CREATE INDEX IF NOT EXISTS idx_videos_category_id ON videos (category_id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_videos_status_queued_at_id ON videos (status, queued_at, id)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_videos_orig_name_trgm ON videos USING GIN (orig_name gin_trgm_ops)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_videos_note_trgm ON videos USING GIN (note gin_trgm_ops)")


# ---------------------------------------------------------------------
# Pool (initialised by main.py lifespan)
# ---------------------------------------------------------------------

pool: ConnectionPool | None = None


def init_pool():
    global pool
    pool = ConnectionPool(
        conninfo=make_conninfo(),
        kwargs={"row_factory": dict_row},
        min_size=2,
        max_size=10,
    )


def close_pool():
    global pool
    if pool is not None:
        pool.close()
