import os
import time
import math
import subprocess
import yaml
import shutil
import uuid
import json
import signal
import logging
from pathlib import Path
from datetime import datetime, UTC

import psutil
import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

DB_HOST = os.getenv("DB_HOST", "postgres")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "eyestream")
DB_USER = os.getenv("DB_USER", "eyestream")
DB_PASSWORD = os.getenv("DB_PASSWORD", "eyestream")
UPLOAD_DIR = os.getenv("UPLOAD_DIR", "/data/uploads")
HLS_DIR = os.getenv("HLS_DIR", "/data/hls")
LADDER_CFG = os.getenv("LADDER_CFG", "/config/ladder.yml")
PUBLIC_BASE = os.getenv("PUBLIC_BASE", "https://localhost")

MAX_PARALLEL_JOBS = int(os.getenv("MAX_PARALLEL_JOBS", "1"))
PROGRESS_POLL_SECONDS = 2
HEALTHCHECK_FILE = "/tmp/.worker_alive"


def touch_healthcheck():
    Path(HEALTHCHECK_FILE).touch()


# ---------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------
# Custom Exceptions
# ---------------------------------------------------------------------

class VideoDeleted(Exception):
    """Raised when the video row was deleted while encoding."""


class VideoCancelled(Exception):
    """Raised when the user requested cancellation."""


# ---------------------------------------------------------------------
# DB
# ---------------------------------------------------------------------

def make_conninfo() -> str:
    return (
        f"host={DB_HOST} port={DB_PORT} dbname={DB_NAME} "
        f"user={DB_USER} password={DB_PASSWORD}"
    )


def wait_for_db(max_attempts: int = 30, delay_seconds: int = 2):
    for attempt in range(max_attempts):
        try:
            with psycopg.connect(make_conninfo()):
                return
        except Exception as exc:
            logger.warning("DB not ready (attempt %d/%d): %s", attempt + 1, max_attempts, exc)
            time.sleep(delay_seconds)
    raise RuntimeError("Could not connect to database after %d attempts" % max_attempts)


def migrate_timestamp_columns(conn):
    """Migrate TEXT timestamp columns to TIMESTAMPTZ (idempotent)."""
    row = conn.execute(
        """
        SELECT data_type FROM information_schema.columns
        WHERE table_name='videos' AND column_name='uploaded_at'
        """
    ).fetchone()

    if not row or row["data_type"] != "text":
        return

    logger.info("Migrating timestamp columns from TEXT to TIMESTAMPTZ...")
    for col in ("uploaded_at", "started_at", "encoded_at", "queued_at"):
        conn.execute(
            f"ALTER TABLE videos ALTER COLUMN {col} "
            f"TYPE TIMESTAMPTZ USING NULLIF({col}, '')::timestamptz"
        )
    logger.info("Timestamp migration complete.")


def ensure_schema(conn):
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS videos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            orig_name TEXT,
            stored_name TEXT,
            uploaded_at TIMESTAMPTZ,
            owner_email TEXT,
            status TEXT,
            progress INTEGER DEFAULT 0,
            playlist_url TEXT,
            poster_url TEXT,
            error TEXT,
            started_at TIMESTAMPTZ,
            ffmpeg_pid INTEGER,
            cancel_requested INTEGER DEFAULT 0,
            eta_seconds INTEGER,
            encoded_at TIMESTAMPTZ,
            duration_seconds DOUBLE PRECISION,
            streams_json TEXT,
            queued_at TIMESTAMPTZ,
            note TEXT DEFAULT ''
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS worker_heartbeat (
            id INTEGER PRIMARY KEY DEFAULT 1,
            last_seen TIMESTAMPTZ,
            status TEXT,
            cpu_percent INTEGER
        )
        """
    )
    conn.execute(
        "INSERT INTO worker_heartbeat (id, last_seen, status) VALUES (1, now(), 'idle') ON CONFLICT DO NOTHING"
    )
    # Migrate: add cpu_percent column if missing
    col = conn.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_name='worker_heartbeat' AND column_name='cpu_percent'"
    ).fetchone()
    if not col:
        conn.execute("ALTER TABLE worker_heartbeat ADD COLUMN cpu_percent INTEGER")
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_videos_status_queued_at_id
        ON videos (status, queued_at, id)
        """
    )
    try:
        conn.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_videos_orig_name_trgm
            ON videos USING GIN (orig_name gin_trgm_ops)
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_videos_note_trgm
            ON videos USING GIN (note gin_trgm_ops)
            """
        )
    except Exception as exc:
        logger.warning("pg_trgm extension not available, trigram indexes skipped: %s", exc)

    migrate_timestamp_columns(conn)


def reset_encoding_jobs(pool: ConnectionPool):
    with pool.connection() as c:
        c.execute(
            """
            UPDATE videos
            SET status='queued',
                progress=0,
                eta_seconds=NULL,
                error='Encoding durch Neustart unterbrochen',
                started_at=NULL,
                ffmpeg_pid=NULL,
                cancel_requested=0
            WHERE status='encoding'
            """
        )


def cleanup_tmp_dirs():
    if not os.path.exists(HLS_DIR):
        return
    for name in os.listdir(HLS_DIR):
        if name.startswith(".tmp_"):
            shutil.rmtree(os.path.join(HLS_DIR, name), ignore_errors=True)


# ---------------------------------------------------------------------
# Media Inspection
# ---------------------------------------------------------------------

def get_duration_seconds(src: str) -> float | None:
    try:
        p = subprocess.run(
            [
                "ffprobe",
                "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1",
                src,
            ],
            capture_output=True,
            text=True,
        )
        return float(p.stdout.strip())
    except Exception as exc:
        logger.warning("get_duration_seconds(%s) failed: %s", src, exc)
        return None


def get_fps(src: str) -> float | None:
    try:
        p = subprocess.run(
            [
                "ffprobe",
                "-v", "error",
                "-select_streams", "v:0",
                "-show_entries", "stream=r_frame_rate",
                "-of", "default=noprint_wrappers=1:nokey=1",
                src,
            ],
            capture_output=True,
            text=True,
        )
        val = p.stdout.strip()
        if "/" in val:
            num, den = val.split("/", 1)
            return float(num) / float(den)
        return float(val)
    except Exception as exc:
        logger.warning("get_fps(%s) failed: %s", src, exc)
        return None


def probe_streams(src: str) -> list:
    try:
        p = subprocess.run(
            [
                "ffprobe",
                "-v", "error",
                "-print_format", "json",
                "-show_streams",
                src,
            ],
            capture_output=True,
            text=True,
        )
        data = json.loads(p.stdout)
        return data.get("streams", [])
    except Exception as exc:
        logger.warning("probe_streams(%s) failed: %s", src, exc)
        return []


def codecs_for_profile(profile: str) -> str:
    v = {
        "baseline": "avc1.42E01E",
        "main": "avc1.4D401F",
        "high": "avc1.640028",
    }.get(profile, "avc1.640028")
    return f'{v},mp4a.40.2'


def width_from_height(h: int) -> int:
    return int(math.floor(h * 16 / 9 / 2) * 2)


def count_segments(path: str) -> int:
    total = 0
    for root, _, files in os.walk(path):
        for f in files:
            if f.endswith(".m4s"):
                total += 1
    return total


def create_poster(src: str, outdir: str):
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-i", src,
            "-ss", "00:00:00",
            "-vframes", "1",
            "-update", "1",
            "-vf", "scale=1280:-2",
            os.path.join(outdir, "poster.jpg"),
        ],
        check=True,
    )


def create_preview_thumbnails(src: str, outdir: str, duration: float, count: int = 6):
    """Generate small preview thumbnails at evenly spaced intervals."""
    if not duration or duration < 2:
        return
    positions = [duration * p for p in [0.10, 0.25, 0.40, 0.55, 0.70, 0.85]]
    previews = []
    for i, t in enumerate(positions[:count]):
        ts = f"{int(t // 3600):02d}:{int(t % 3600 // 60):02d}:{t % 60:06.3f}"
        fname = f"preview_{i}.jpg"
        try:
            subprocess.run(
                [
                    "ffmpeg", "-y",
                    "-ss", ts,
                    "-i", src,
                    "-vframes", "1",
                    "-update", "1",
                    "-vf", "scale=320:-2",
                    os.path.join(outdir, fname),
                ],
                check=True,
                capture_output=True,
            )
            previews.append({"t": round(t, 2), "f": fname})
        except Exception as exc:
            logger.warning("Preview thumbnail %d failed at %.1fs: %s", i, t, exc)

    if previews:
        with open(os.path.join(outdir, "previews.json"), "w") as f:
            json.dump(previews, f)
        logger.info("Generated %d preview thumbnails in %s", len(previews), outdir)

    # Large previews for embed player
    previews_lg = []
    for i, t in enumerate(positions[:count]):
        ts = f"{int(t // 3600):02d}:{int(t % 3600 // 60):02d}:{t % 60:06.3f}"
        fname = f"preview_lg_{i}.jpg"
        try:
            subprocess.run(
                [
                    "ffmpeg", "-y",
                    "-ss", ts,
                    "-i", src,
                    "-vframes", "1",
                    "-update", "1",
                    "-vf", "scale=960:-2",
                    os.path.join(outdir, fname),
                ],
                check=True,
                capture_output=True,
            )
            previews_lg.append({"t": round(t, 2), "f": fname})
        except Exception as exc:
            logger.warning("Large preview thumbnail %d failed at %.1fs: %s", i, t, exc)

    if previews_lg:
        with open(os.path.join(outdir, "previews_lg.json"), "w") as f:
            json.dump(previews_lg, f)
        logger.info("Generated %d large preview thumbnails in %s", len(previews_lg), outdir)


# ---------------------------------------------------------------------
# Process handling
# ---------------------------------------------------------------------

def kill_process_group(pid: int):
    """
    ffmpeg wird in eigener Prozessgruppe gestartet (setsid),
    darum ist pgid == pid und wir killen die ganze Gruppe.
    """
    if not pid:
        return
    try:
        os.killpg(pid, signal.SIGTERM)
        time.sleep(2)
        os.killpg(pid, signal.SIGKILL)
    except OSError as exc:
        logger.debug("kill_process_group(%d): %s", pid, exc)


# ---------------------------------------------------------------------
# Encoding
# ---------------------------------------------------------------------

def count_segments_for(path: str, prefix: str) -> int:
    total = 0
    for f in os.listdir(path):
        if f.startswith(prefix + "_") and f.endswith(".m4s"):
            total += 1
    return total


def encode(job_id: int, src: str, tmp_dir: str, cfg: dict, pool: ConnectionPool):
    Path(tmp_dir).mkdir(parents=True, exist_ok=True)

    hls_time = int(cfg.get("hls_time_seconds", 6))
    renditions = cfg["renditions"]

    duration = get_duration_seconds(src)
    fps = get_fps(src) or 25.0
    gop = max(24, int(round(fps * hls_time)))

    expected = math.ceil(duration / hls_time) if duration else None

    # Weight each rendition by height — higher res = more work, but decoding cost is fixed
    weights = [int(r["height"]) for r in renditions]
    total_weight = sum(weights)

    master = ["#EXTM3U", "#EXT-X-VERSION:3"]
    start_time = datetime.now(UTC)
    completed_weight = 0

    for ridx, r in enumerate(renditions):
        playlist = f"{r['name']}.m3u8"
        init_file = f"init_{r['name']}.mp4"
        segments = os.path.join(tmp_dir, f"{r['name']}_%05d.m4s")

        h = int(r["height"])
        w = width_from_height(h)

        x264_extra = []
        if r["profile"] == "baseline":
            x264_extra = ["-bf", "0", "-refs", "1"]

        cmd = [
            "ffmpeg", "-y",
            "-err_detect", "ignore_err",
            "-fflags", "+genpts",
            "-i", src,
            "-map", "0:v:0",
            "-map", "0:a:0?",
            "-vf",
            f"scale=w={w}:h={h}:force_original_aspect_ratio=decrease,"
            "scale=trunc(iw/2)*2:trunc(ih/2)*2",
            "-c:v", "libx264",
            "-profile:v", r["profile"],
            "-preset", "slow",
            "-pix_fmt", "yuv420p",
            "-b:v", r["v_bitrate"],
            "-maxrate", r.get("maxrate", ""),
            "-bufsize", r.get("bufsize", ""),
            "-g", str(gop),
            "-keyint_min", str(gop),
            "-sc_threshold", "0",
            "-force_key_frames", f"expr:gte(t,n_forced*{hls_time})",
            *x264_extra,
            "-c:a", "aac",
            "-b:a", r["a_bitrate"],
            "-ac", "2",
            "-hls_time", str(hls_time),
            "-hls_playlist_type", "vod",
            "-hls_segment_type", "fmp4",
            "-hls_fmp4_init_filename", init_file,
            "-hls_flags", "independent_segments",
            "-hls_list_size", "0",
            "-hls_segment_filename", segments,
            "-f", "hls",
            os.path.join(tmp_dir, playlist),
        ]

        cmd = [c for c in cmd if c]

        # setsid => neue Prozessgruppe
        proc = subprocess.Popen(cmd, preexec_fn=os.setsid)

        with pool.connection() as c:
            c.execute("UPDATE videos SET ffmpeg_pid=%s WHERE id=%s", (proc.pid, job_id))

        while proc.poll() is None:
            with pool.connection() as c:
                row = c.execute(
                    "SELECT cancel_requested FROM videos WHERE id=%s",
                    (job_id,),
                ).fetchone()

            # Wenn Row weg ist -> delete gedrückt
            if not row:
                kill_process_group(proc.pid)
                raise VideoDeleted()

            # Cancel
            if row["cancel_requested"]:
                kill_process_group(proc.pid)
                raise VideoCancelled()

            # Progress (weighted by rendition pixel count)
            if expected and total_weight:
                current_segs = count_segments_for(tmp_dir, r["name"])
                if current_segs > 0:
                    current_fraction = min(1.0, current_segs / expected)
                    weighted_done = completed_weight + weights[ridx] * current_fraction
                    pct = min(99, int(weighted_done / total_weight * 100))

                    elapsed = (datetime.now(UTC) - start_time).total_seconds()
                    if weighted_done > 0:
                        eta_seconds = max(0, int(elapsed / weighted_done * (total_weight - weighted_done)))
                    else:
                        eta_seconds = 0
                    cpu = int(psutil.cpu_percent(interval=None))

                    with pool.connection() as c:
                        c.execute(
                            "UPDATE videos SET progress=%s, eta_seconds=%s, cpu_percent=%s WHERE id=%s",
                            (pct, eta_seconds, cpu, job_id),
                        )
                        c.execute(
                            "UPDATE worker_heartbeat SET last_seen=now(), status='encoding', cpu_percent=%s WHERE id=1",
                            (cpu,),
                        )
                        touch_healthcheck()

            time.sleep(PROGRESS_POLL_SECONDS)

        if proc.returncode != 0:
            raise RuntimeError(f"ffmpeg failed for {r['name']} (exit code {proc.returncode})")

        completed_weight += weights[ridx]

        # Zielwerte in master (ABR-Hints)
        bw = (
            int(r["v_bitrate"].replace("k", "")) +
            int(r["a_bitrate"].replace("k", ""))
        ) * 1000

        avg_bw = int(bw * 0.92)
        codecs = codecs_for_profile(r["profile"])

        master.append(
            f'#EXT-X-STREAM-INF:BANDWIDTH={bw},'
            f'AVERAGE-BANDWIDTH={avg_bw},'
            f'RESOLUTION={w}x{h},'
            f'FRAME-RATE={fps:.3f},'
            f'CODECS="{codecs}"'
        )
        master.append(playlist)

    with open(os.path.join(tmp_dir, "master.m3u8"), "w") as f:
        f.write("\n".join(master) + "\n")


# ---------------------------------------------------------------------
# Worker Loop
# ---------------------------------------------------------------------

def main():
    wait_for_db()

    pool = ConnectionPool(
        conninfo=make_conninfo(),
        kwargs={"row_factory": dict_row},
        min_size=1,
        max_size=3,
    )

    with pool.connection() as c:
        ensure_schema(c)

    reset_encoding_jobs(pool)
    cleanup_tmp_dirs()

    with open(LADDER_CFG, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    logger.info("Worker started. MAX_PARALLEL_JOBS=%d", MAX_PARALLEL_JOBS)
    psutil.cpu_percent(interval=None)  # prime first measurement

    while True:
        job = None

        with pool.connection() as c:
            c.execute("UPDATE worker_heartbeat SET last_seen=now(), status='polling', cpu_percent=%s WHERE id=1", (int(psutil.cpu_percent(interval=None)),))
            touch_healthcheck()
            running = c.execute(
                "SELECT COUNT(*) AS total FROM videos WHERE status='encoding'"
            ).fetchone()["total"]

            if running < MAX_PARALLEL_JOBS:
                job = c.execute(
                    """
                    WITH candidate AS (
                        SELECT id
                        FROM videos
                        WHERE status='queued'
                        ORDER BY queued_at ASC NULLS LAST, id ASC
                        FOR UPDATE SKIP LOCKED
                        LIMIT 1
                    )
                    UPDATE videos v
                    SET status='encoding',
                        progress=0,
                        eta_seconds=NULL,
                        started_at=%s,
                        error=NULL,
                        cancel_requested=0
                    FROM candidate
                    WHERE v.id = candidate.id
                    RETURNING v.*
                    """,
                    (datetime.now(UTC),),
                ).fetchone()

        if not job:
            # Idle: generate missing preview thumbnails for existing videos
            generated = False
            try:
                with pool.connection() as c:
                    candidate = c.execute(
                        """
                        SELECT id, stored_name, duration_seconds
                        FROM videos
                        WHERE status='ready'
                          AND duration_seconds IS NOT NULL
                        ORDER BY id
                        """
                    ).fetchall()
                for v in candidate:
                    vid_dir = os.path.join(HLS_DIR, str(v["id"]))
                    dis_dir = os.path.join(HLS_DIR, f".disabled_{v['id']}")
                    actual_dir = dis_dir if os.path.isdir(dis_dir) else vid_dir
                    pj = os.path.join(actual_dir, "previews.json")
                    pj_lg = os.path.join(actual_dir, "previews_lg.json")
                    if os.path.exists(pj) and os.path.exists(pj_lg):
                        continue
                    vidsrc = os.path.join(UPLOAD_DIR, v["stored_name"])
                    if not os.path.exists(vidsrc):
                        continue
                    if not os.path.isdir(actual_dir):
                        continue
                    with pool.connection() as c:
                        c.execute("UPDATE worker_heartbeat SET last_seen=now(), status='previews', cpu_percent=%s WHERE id=1", (int(psutil.cpu_percent(interval=None)),))
                        touch_healthcheck()
                    logger.info("Generating missing preview thumbnails for video id=%d", v["id"])
                    create_preview_thumbnails(vidsrc, actual_dir, v["duration_seconds"])
                    generated = True
                    break  # max 1 per idle cycle
            except Exception as exc:
                logger.warning("Idle preview generation failed: %s", exc)

            if not generated:
                with pool.connection() as c:
                    c.execute("UPDATE worker_heartbeat SET last_seen=now(), status='idle', cpu_percent=%s WHERE id=1", (int(psutil.cpu_percent(interval=None)),))
                    touch_healthcheck()

            time.sleep(5)
            continue

        logger.info("Starting encode for job id=%d (%s)", job["id"], job["orig_name"])
        with pool.connection() as c:
            c.execute("UPDATE worker_heartbeat SET last_seen=now(), status='encoding', cpu_percent=%s WHERE id=1", (int(psutil.cpu_percent(interval=None)),))
            touch_healthcheck()

        src = os.path.join(UPLOAD_DIR, job["stored_name"])
        disabled_dir = os.path.join(HLS_DIR, f".disabled_{job['id']}")
        is_disabled = os.path.exists(disabled_dir)
        final_dir = disabled_dir if is_disabled else os.path.join(HLS_DIR, str(job["id"]))
        tmp_dir = os.path.join(HLS_DIR, f".tmp_{job['id']}_{uuid.uuid4().hex[:8]}")

        try:
            Path(tmp_dir).mkdir(parents=True, exist_ok=True)
            existing_poster = os.path.join(final_dir, "poster.jpg")
            has_custom_poster = os.path.exists(existing_poster)

            if has_custom_poster:
                # Preserve existing (possibly manually set) poster
                shutil.copy2(existing_poster, os.path.join(tmp_dir, "poster.jpg"))
            else:
                # Generate early poster so it's visible during encoding
                try:
                    Path(final_dir).mkdir(parents=True, exist_ok=True)
                    create_poster(src, final_dir)
                    shutil.copy2(os.path.join(final_dir, "poster.jpg"), os.path.join(tmp_dir, "poster.jpg"))
                    with pool.connection() as c:
                        c.execute(
                            "UPDATE videos SET poster_url=%s WHERE id=%s",
                            (f"{PUBLIC_BASE}/{job['id']}/poster.jpg", job["id"]),
                        )
                except Exception as exc:
                    logger.warning("Early poster generation failed for job %d: %s", job["id"], exc)

            encode(job["id"], src, tmp_dir, cfg, pool)

            # Only generate new poster if there wasn't a custom one
            if not has_custom_poster:
                create_poster(src, tmp_dir)

            streams = probe_streams(src)
            duration = get_duration_seconds(src)

            try:
                create_preview_thumbnails(src, tmp_dir, duration)
            except Exception as exc:
                logger.warning("Preview thumbnails failed for job %d: %s", job["id"], exc)

            # atomic replace: erst am Ende umschalten
            if os.path.exists(final_dir):
                old_dir = final_dir + ".old"
                os.rename(final_dir, old_dir)
                os.rename(tmp_dir, final_dir)
                shutil.rmtree(old_dir, ignore_errors=True)
            else:
                os.rename(tmp_dir, final_dir)

            with pool.connection() as c:
                c.execute(
                    """
                    UPDATE videos
                    SET status='ready',
                        progress=100,
                        eta_seconds=0,
                        playlist_url=%s,
                        poster_url=%s,
                        encoded_at=%s,
                        duration_seconds=%s,
                        streams_json=%s,
                        ffmpeg_pid=NULL,
                        cpu_percent=NULL
                    WHERE id=%s
                    """,
                    (
                        f"{PUBLIC_BASE}/{job['id']}/master.m3u8",
                        f"{PUBLIC_BASE}/{job['id']}/poster.jpg",
                        datetime.now(UTC),
                        duration,
                        json.dumps(streams),
                        job["id"],
                    ),
                )

            logger.info("Encode complete for job id=%d", job["id"])

        except VideoDeleted:
            logger.info("Job id=%d was deleted during encoding, skipping DB update.", job["id"])
            if os.path.exists(tmp_dir):
                shutil.rmtree(tmp_dir, ignore_errors=True)

        except VideoCancelled:
            logger.info("Job id=%d was cancelled.", job["id"])
            if os.path.exists(tmp_dir):
                shutil.rmtree(tmp_dir, ignore_errors=True)
            with pool.connection() as c:
                c.execute(
                    "UPDATE videos SET status='cancelled', error=NULL, ffmpeg_pid=NULL, cpu_percent=NULL WHERE id=%s",
                    (job["id"],),
                )

        except Exception as exc:
            logger.exception("Encode failed for job id=%d: %s", job["id"], exc)
            if os.path.exists(tmp_dir):
                shutil.rmtree(tmp_dir, ignore_errors=True)
            with pool.connection() as c:
                c.execute(
                    "UPDATE videos SET status='failed', error=%s, ffmpeg_pid=NULL, cpu_percent=NULL WHERE id=%s",
                    (str(exc)[:500].replace(UPLOAD_DIR, "...").replace(HLS_DIR, "..."), job["id"]),
                )

        time.sleep(1)


if __name__ == "__main__":
    main()
